/*.cc generated by pgen*/

#include "grammar.h"
#include "token.h"
#include "bitset.h"
#include "graminit.h"

std::vector<Label> labels={
    {0,"EMPTY"},
    {256,""},
    {4,""},
    {289,""},
    {305,""},
    {257,""},
    {288,""},
    {0,""},
    {258,""},
    {286,""},
    {259,""},
    {1,"def"},
    {1,""},
    {260,""},
    {11,""},
    {304,""},
    {7,""},
    {261,""},
    {8,""},
    {262,""},
    {23,""},
    {263,""},
    {16,""},
    {264,""},
    {1,"if"},
    {1,"else"},
    {265,""},
    {1,"or"},
    {266,""},
    {1,"and"},
    {1,"not"},
    {267,""},
    {269,""},
    {268,""},
    {21,""},
    {22,""},
    {30,""},
    {34,""},
    {32,""},
    {31,""},
    {270,""},
    {13,""},
    {271,""},
    {27,""},
    {272,""},
    {20,""},
    {273,""},
    {33,""},
    {35,""},
    {274,""},
    {14,""},
    {15,""},
    {275,""},
    {12,""},
    {18,""},
    {24,""},
    {41,""},
    {28,""},
    {276,""},
    {277,""},
    {39,""},
    {278,""},
    {279,""},
    {9,""},
    {284,""},
    {10,""},
    {25,""},
    {310,""},
    {26,""},
    {2,""},
    {3,""},
    {52,""},
    {1,"None"},
    {1,"True"},
    {1,"False"},
    {285,""},
    {280,""},
    {19,""},
    {281,""},
    {282,""},
    {283,""},
    {301,""},
    {287,""},
    {290,""},
    {17,""},
    {293,""},
    {295,""},
    {294,""},
    {291,""},
    {292,""},
    {1,"nonlocal"},
    {1,"global"},
    {303,""},
    {1,"pass"},
    {296,""},
    {297,""},
    {298,""},
    {299,""},
    {1,"break"},
    {1,"continue"},
    {1,"return"},
    {1,"yield"},
    {300,""},
    {302,""},
    {1,"for"},
    {1,"in"},
    {36,""},
    {37,""},
    {40,""},
    {42,""},
    {44,""},
    {45,""},
    {43,""},
    {46,""},
    {48,""},
    {49,""},
    {50,""},
    {51,""},
    {5,""},
    {6,""},
    {306,""},
    {307,""},
    {308,""},
    {309,""},
    {1,"elif"},
    {1,"while"},
    {1,"class"},
};
std::vector<Arc> arcs_0_0={{2,1},{3,2},{4,3},};
std::vector<Arc> arcs_0_1={{0,1},};
std::vector<Arc> arcs_0_2={{0,2},};
std::vector<Arc> arcs_0_3={{2,4},};
std::vector<Arc> arcs_0_4={{0,4},};
std::vector<DFAState> states_0={arcs_0_0,arcs_0_1,arcs_0_2,arcs_0_3,arcs_0_4,};
DFA dfa_0={256,"single_input",0,states_0,{64,"\004\030\001\101\000\000\014\202\344\007\000\054\074\001\000\140"}};

std::vector<Arc> arcs_1_0={{2,1},{6,2},{7,3},};
std::vector<Arc> arcs_1_1={{2,1},{6,2},{7,3},};
std::vector<Arc> arcs_1_2={{2,1},{6,2},{7,3},};
std::vector<Arc> arcs_1_3={{0,3},};
std::vector<DFAState> states_1={arcs_1_0,arcs_1_1,arcs_1_2,arcs_1_3,};
DFA dfa_1={257,"file_input",0,states_1,{64,"\204\030\001\101\000\000\014\202\344\007\000\054\074\001\000\140"}};

std::vector<Arc> arcs_2_0={{9,1},};
std::vector<Arc> arcs_2_1={{2,2},{7,3},};
std::vector<Arc> arcs_2_2={{2,2},{7,3},};
std::vector<Arc> arcs_2_3={{0,3},};
std::vector<DFAState> states_2={arcs_2_0,arcs_2_1,arcs_2_2,arcs_2_3,};
DFA dfa_2={258,"eval_input",0,states_2,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_3_0={{11,1},};
std::vector<Arc> arcs_3_1={{12,2},};
std::vector<Arc> arcs_3_2={{13,3},};
std::vector<Arc> arcs_3_3={{14,4},};
std::vector<Arc> arcs_3_4={{15,5},};
std::vector<Arc> arcs_3_5={{0,5},};
std::vector<DFAState> states_3={arcs_3_0,arcs_3_1,arcs_3_2,arcs_3_3,arcs_3_4,arcs_3_5,};
DFA dfa_3={259,"funcdef",0,states_3,{64,"\000\010\000\000\000\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_4_0={{16,1},};
std::vector<Arc> arcs_4_1={{17,2},{18,3},};
std::vector<Arc> arcs_4_2={{18,3},};
std::vector<Arc> arcs_4_3={{0,3},};
std::vector<DFAState> states_4={arcs_4_0,arcs_4_1,arcs_4_2,arcs_4_3,};
DFA dfa_4={260,"parameters",0,states_4,{64,"\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_5_0={{19,1},};
std::vector<Arc> arcs_5_1={{20,2},{22,3},{22,3},{0,1},};
std::vector<Arc> arcs_5_2={{21,4},};
std::vector<Arc> arcs_5_3={{19,5},{0,3},};
std::vector<Arc> arcs_5_4={{22,3},{22,3},{0,4},};
std::vector<Arc> arcs_5_5={{22,3},{20,6},{22,3},{0,5},};
std::vector<Arc> arcs_5_6={{21,7},};
std::vector<Arc> arcs_5_7={{22,3},{22,3},{0,7},};
std::vector<DFAState> states_5={arcs_5_0,arcs_5_1,arcs_5_2,arcs_5_3,arcs_5_4,arcs_5_5,arcs_5_6,arcs_5_7,};
DFA dfa_5={261,"typedargslist",0,states_5,{64,"\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_6_0={{12,1},};
std::vector<Arc> arcs_6_1={{0,1},};
std::vector<DFAState> states_6={arcs_6_0,arcs_6_1,};
DFA dfa_6={262,"tfpdef",0,states_6,{64,"\000\020\000\000\000\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_7_0={{23,1},};
std::vector<Arc> arcs_7_1={{24,2},{0,1},};
std::vector<Arc> arcs_7_2={{23,3},};
std::vector<Arc> arcs_7_3={{25,4},};
std::vector<Arc> arcs_7_4={{21,5},};
std::vector<Arc> arcs_7_5={{0,5},};
std::vector<DFAState> states_7={arcs_7_0,arcs_7_1,arcs_7_2,arcs_7_3,arcs_7_4,arcs_7_5,};
DFA dfa_7={263,"test",0,states_7,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_8_0={{26,1},};
std::vector<Arc> arcs_8_1={{27,2},{0,1},};
std::vector<Arc> arcs_8_2={{26,3},};
std::vector<Arc> arcs_8_3={{27,2},{0,3},};
std::vector<DFAState> states_8={arcs_8_0,arcs_8_1,arcs_8_2,arcs_8_3,};
DFA dfa_8={264,"or_test",0,states_8,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_9_0={{28,1},};
std::vector<Arc> arcs_9_1={{29,2},{0,1},};
std::vector<Arc> arcs_9_2={{28,3},};
std::vector<Arc> arcs_9_3={{29,2},{0,3},};
std::vector<DFAState> states_9={arcs_9_0,arcs_9_1,arcs_9_2,arcs_9_3,};
DFA dfa_9={265,"and_test",0,states_9,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_10_0={{30,1},{31,2},};
std::vector<Arc> arcs_10_1={{28,3},};
std::vector<Arc> arcs_10_2={{0,2},};
std::vector<Arc> arcs_10_3={{0,3},};
std::vector<DFAState> states_10={arcs_10_0,arcs_10_1,arcs_10_2,arcs_10_3,};
DFA dfa_10={266,"not_test",0,states_10,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_11_0={{32,1},};
std::vector<Arc> arcs_11_1={{33,2},{0,1},};
std::vector<Arc> arcs_11_2={{32,3},};
std::vector<Arc> arcs_11_3={{33,2},{0,3},};
std::vector<DFAState> states_11={arcs_11_0,arcs_11_1,arcs_11_2,arcs_11_3,};
DFA dfa_11={267,"comparison",0,states_11,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_12_0={{34,1},{35,2},{36,3},{37,4},{38,5},{39,6},};
std::vector<Arc> arcs_12_1={{0,1},};
std::vector<Arc> arcs_12_2={{0,2},};
std::vector<Arc> arcs_12_3={{0,3},};
std::vector<Arc> arcs_12_4={{0,4},};
std::vector<Arc> arcs_12_5={{0,5},};
std::vector<Arc> arcs_12_6={{0,6},};
std::vector<DFAState> states_12={arcs_12_0,arcs_12_1,arcs_12_2,arcs_12_3,arcs_12_4,arcs_12_5,arcs_12_6,};
DFA dfa_12={268,"comp_op",0,states_12,{64,"\000\000\000\000\374\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_13_0={{40,1},};
std::vector<Arc> arcs_13_1={{41,2},{0,1},};
std::vector<Arc> arcs_13_2={{40,3},};
std::vector<Arc> arcs_13_3={{41,2},{0,3},};
std::vector<DFAState> states_13={arcs_13_0,arcs_13_1,arcs_13_2,arcs_13_3,};
DFA dfa_13={269,"expr",0,states_13,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_14_0={{42,1},};
std::vector<Arc> arcs_14_1={{43,2},{0,1},};
std::vector<Arc> arcs_14_2={{42,3},};
std::vector<Arc> arcs_14_3={{43,2},{0,3},};
std::vector<DFAState> states_14={arcs_14_0,arcs_14_1,arcs_14_2,arcs_14_3,};
DFA dfa_14={270,"xor_expr",0,states_14,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_15_0={{44,1},};
std::vector<Arc> arcs_15_1={{45,2},{0,1},};
std::vector<Arc> arcs_15_2={{44,3},};
std::vector<Arc> arcs_15_3={{45,2},{0,3},};
std::vector<DFAState> states_15={arcs_15_0,arcs_15_1,arcs_15_2,arcs_15_3,};
DFA dfa_15={271,"and_expr",0,states_15,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_16_0={{46,1},};
std::vector<Arc> arcs_16_1={{47,2},{48,3},{0,1},};
std::vector<Arc> arcs_16_2={{46,4},};
std::vector<Arc> arcs_16_3={{46,4},};
std::vector<Arc> arcs_16_4={{47,2},{48,3},{0,4},};
std::vector<DFAState> states_16={arcs_16_0,arcs_16_1,arcs_16_2,arcs_16_3,arcs_16_4,};
DFA dfa_16={272,"shift_expr",0,states_16,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_17_0={{49,1},};
std::vector<Arc> arcs_17_1={{50,2},{51,3},{0,1},};
std::vector<Arc> arcs_17_2={{49,4},};
std::vector<Arc> arcs_17_3={{49,4},};
std::vector<Arc> arcs_17_4={{50,2},{51,3},{0,4},};
std::vector<DFAState> states_17={arcs_17_0,arcs_17_1,arcs_17_2,arcs_17_3,arcs_17_4,};
DFA dfa_17={273,"arith_expr",0,states_17,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_18_0={{52,1},};
std::vector<Arc> arcs_18_1={{53,2},{54,3},{55,4},{56,5},{0,1},};
std::vector<Arc> arcs_18_2={{52,6},};
std::vector<Arc> arcs_18_3={{52,6},};
std::vector<Arc> arcs_18_4={{52,6},};
std::vector<Arc> arcs_18_5={{52,6},};
std::vector<Arc> arcs_18_6={{53,2},{54,3},{55,4},{56,5},{0,6},};
std::vector<DFAState> states_18={arcs_18_0,arcs_18_1,arcs_18_2,arcs_18_3,arcs_18_4,arcs_18_5,arcs_18_6,};
DFA dfa_18={274,"term",0,states_18,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_19_0={{50,1},{51,2},{57,3},{58,4},};
std::vector<Arc> arcs_19_1={{52,5},};
std::vector<Arc> arcs_19_2={{52,5},};
std::vector<Arc> arcs_19_3={{52,5},};
std::vector<Arc> arcs_19_4={{0,4},};
std::vector<Arc> arcs_19_5={{0,5},};
std::vector<DFAState> states_19={arcs_19_0,arcs_19_1,arcs_19_2,arcs_19_3,arcs_19_4,arcs_19_5,};
DFA dfa_19={275,"factor",0,states_19,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_20_0={{59,1},};
std::vector<Arc> arcs_20_1={{60,2},{0,1},};
std::vector<Arc> arcs_20_2={{52,3},};
std::vector<Arc> arcs_20_3={{0,3},};
std::vector<DFAState> states_20={arcs_20_0,arcs_20_1,arcs_20_2,arcs_20_3,};
DFA dfa_20={276,"power",0,states_20,{64,"\000\020\001\000\000\000\000\200\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_21_0={{61,1},};
std::vector<Arc> arcs_21_1={{62,2},{0,1},};
std::vector<Arc> arcs_21_2={{62,2},{0,2},};
std::vector<DFAState> states_21={arcs_21_0,arcs_21_1,arcs_21_2,};
DFA dfa_21={277,"atom_expr",0,states_21,{64,"\000\020\001\000\000\000\000\200\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_22_0={{16,1},{63,2},{66,3},{12,4},{69,5},{70,6},{71,7},{72,8},{73,9},{74,10},};
std::vector<Arc> arcs_22_1={{9,11},{18,12},};
std::vector<Arc> arcs_22_2={{64,13},{65,14},};
std::vector<Arc> arcs_22_3={{67,15},{68,16},};
std::vector<Arc> arcs_22_4={{0,4},};
std::vector<Arc> arcs_22_5={{0,5},};
std::vector<Arc> arcs_22_6={{70,6},{0,6},};
std::vector<Arc> arcs_22_7={{0,7},};
std::vector<Arc> arcs_22_8={{0,8},};
std::vector<Arc> arcs_22_9={{0,9},};
std::vector<Arc> arcs_22_10={{0,10},};
std::vector<Arc> arcs_22_11={{18,12},};
std::vector<Arc> arcs_22_12={{0,12},};
std::vector<Arc> arcs_22_13={{65,14},};
std::vector<Arc> arcs_22_14={{0,14},};
std::vector<Arc> arcs_22_15={{68,16},};
std::vector<Arc> arcs_22_16={{0,16},};
std::vector<DFAState> states_22={arcs_22_0,arcs_22_1,arcs_22_2,arcs_22_3,arcs_22_4,arcs_22_5,arcs_22_6,arcs_22_7,arcs_22_8,arcs_22_9,arcs_22_10,arcs_22_11,arcs_22_12,arcs_22_13,arcs_22_14,arcs_22_15,arcs_22_16,};
DFA dfa_22={278,"atom",0,states_22,{64,"\000\020\001\000\000\000\000\200\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_23_0={{16,1},{63,2},{77,3},};
std::vector<Arc> arcs_23_1={{75,4},{18,5},};
std::vector<Arc> arcs_23_2={{76,6},};
std::vector<Arc> arcs_23_3={{12,7},};
std::vector<Arc> arcs_23_4={{18,5},};
std::vector<Arc> arcs_23_5={{0,5},};
std::vector<Arc> arcs_23_6={{65,8},};
std::vector<Arc> arcs_23_7={{0,7},};
std::vector<Arc> arcs_23_8={{0,8},};
std::vector<DFAState> states_23={arcs_23_0,arcs_23_1,arcs_23_2,arcs_23_3,arcs_23_4,arcs_23_5,arcs_23_6,arcs_23_7,arcs_23_8,};
DFA dfa_23={279,"trailer",0,states_23,{64,"\000\000\001\000\000\000\000\200\000\040\000\000\000\000\000\000"}};

std::vector<Arc> arcs_24_0={{78,1},};
std::vector<Arc> arcs_24_1={{22,2},{22,2},{0,1},};
std::vector<Arc> arcs_24_2={{78,3},{0,2},};
std::vector<Arc> arcs_24_3={{22,2},{22,2},{0,3},};
std::vector<DFAState> states_24={arcs_24_0,arcs_24_1,arcs_24_2,arcs_24_3,};
DFA dfa_24={280,"subscriptlist",0,states_24,{64,"\000\120\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_25_0={{21,1},{21,1},{14,2},};
std::vector<Arc> arcs_25_1={{14,2},{0,1},};
std::vector<Arc> arcs_25_2={{21,3},{79,4},{0,2},};
std::vector<Arc> arcs_25_3={{79,4},{0,3},};
std::vector<Arc> arcs_25_4={{0,4},};
std::vector<DFAState> states_25={arcs_25_0,arcs_25_1,arcs_25_2,arcs_25_3,arcs_25_4,};
DFA dfa_25={281,"subscript",0,states_25,{64,"\000\120\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_26_0={{14,1},};
std::vector<Arc> arcs_26_1={{21,2},{0,1},};
std::vector<Arc> arcs_26_2={{0,2},};
std::vector<DFAState> states_26={arcs_26_0,arcs_26_1,arcs_26_2,};
DFA dfa_26={282,"sliceop",0,states_26,{64,"\000\100\000\000\000\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_27_0={{21,1},{21,1},};
std::vector<Arc> arcs_27_1={{20,2},{0,1},};
std::vector<Arc> arcs_27_2={{21,3},};
std::vector<Arc> arcs_27_3={{0,3},};
std::vector<DFAState> states_27={arcs_27_0,arcs_27_1,arcs_27_2,arcs_27_3,};
DFA dfa_27={283,"argument",0,states_27,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_28_0={{21,1},};
std::vector<Arc> arcs_28_1={{81,2},{22,3},{22,3},{0,1},};
std::vector<Arc> arcs_28_2={{0,2},};
std::vector<Arc> arcs_28_3={{21,4},{0,3},};
std::vector<Arc> arcs_28_4={{22,3},{22,3},{0,4},};
std::vector<DFAState> states_28={arcs_28_0,arcs_28_1,arcs_28_2,arcs_28_3,arcs_28_4,};
DFA dfa_28={284,"testlist_comp",0,states_28,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_29_0={{80,1},};
std::vector<Arc> arcs_29_1={{22,2},{22,2},{0,1},};
std::vector<Arc> arcs_29_2={{80,3},{0,2},};
std::vector<Arc> arcs_29_3={{22,2},{22,2},{0,3},};
std::vector<DFAState> states_29={arcs_29_0,arcs_29_1,arcs_29_2,arcs_29_3,};
DFA dfa_29={285,"arglist",0,states_29,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_30_0={{21,1},};
std::vector<Arc> arcs_30_1={{22,2},{22,2},{0,1},};
std::vector<Arc> arcs_30_2={{21,3},{0,2},};
std::vector<Arc> arcs_30_3={{22,2},{22,2},{0,3},};
std::vector<DFAState> states_30={arcs_30_0,arcs_30_1,arcs_30_2,arcs_30_3,};
DFA dfa_30={286,"testlist",0,states_30,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_31_0={{32,1},};
std::vector<Arc> arcs_31_1={{22,2},{22,2},{0,1},};
std::vector<Arc> arcs_31_2={{32,3},{0,2},};
std::vector<Arc> arcs_31_3={{22,2},{22,2},{0,3},};
std::vector<DFAState> states_31={arcs_31_0,arcs_31_1,arcs_31_2,arcs_31_3,};
DFA dfa_31={287,"exprlist",0,states_31,{64,"\000\020\001\000\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_32_0={{3,1},{4,2},};
std::vector<Arc> arcs_32_1={{0,1},};
std::vector<Arc> arcs_32_2={{0,2},};
std::vector<DFAState> states_32={arcs_32_0,arcs_32_1,arcs_32_2,};
DFA dfa_32={288,"stmt",0,states_32,{64,"\000\030\001\101\000\000\014\202\344\007\000\054\074\001\000\140"}};

std::vector<Arc> arcs_33_0={{83,1},};
std::vector<Arc> arcs_33_1={{84,2},{84,2},{2,3},};
std::vector<Arc> arcs_33_2={{83,4},{2,3},};
std::vector<Arc> arcs_33_3={{0,3},};
std::vector<Arc> arcs_33_4={{84,2},{84,2},{2,3},};
std::vector<DFAState> states_33={arcs_33_0,arcs_33_1,arcs_33_2,arcs_33_3,arcs_33_4,};
DFA dfa_33={289,"simple_stmt",0,states_33,{64,"\000\020\001\100\000\000\014\202\344\007\000\054\074\000\000\000"}};

std::vector<Arc> arcs_34_0={{85,1},{86,2},{87,3},{88,4},{89,5},};
std::vector<Arc> arcs_34_1={{0,1},};
std::vector<Arc> arcs_34_2={{0,2},};
std::vector<Arc> arcs_34_3={{0,3},};
std::vector<Arc> arcs_34_4={{0,4},};
std::vector<Arc> arcs_34_5={{0,5},};
std::vector<DFAState> states_34={arcs_34_0,arcs_34_1,arcs_34_2,arcs_34_3,arcs_34_4,arcs_34_5,};
DFA dfa_34={290,"small_stmt",0,states_34,{64,"\000\020\001\100\000\000\014\202\344\007\000\054\074\000\000\000"}};

std::vector<Arc> arcs_35_0={{90,1},};
std::vector<Arc> arcs_35_1={{12,2},};
std::vector<Arc> arcs_35_2={{22,3},{0,2},};
std::vector<Arc> arcs_35_3={{12,4},};
std::vector<Arc> arcs_35_4={{22,3},{0,4},};
std::vector<DFAState> states_35={arcs_35_0,arcs_35_1,arcs_35_2,arcs_35_3,arcs_35_4,};
DFA dfa_35={291,"nonlocal_stmt",0,states_35,{64,"\000\000\000\000\000\000\000\000\000\000\000\004\000\000\000\000"}};

std::vector<Arc> arcs_36_0={{91,1},};
std::vector<Arc> arcs_36_1={{12,2},};
std::vector<Arc> arcs_36_2={{22,3},{0,2},};
std::vector<Arc> arcs_36_3={{12,4},};
std::vector<Arc> arcs_36_4={{22,3},{0,4},};
std::vector<DFAState> states_36={arcs_36_0,arcs_36_1,arcs_36_2,arcs_36_3,arcs_36_4,};
DFA dfa_36={292,"global_stmt",0,states_36,{64,"\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000\000"}};

std::vector<Arc> arcs_37_0={{9,1},};
std::vector<Arc> arcs_37_1={{92,2},{20,3},{0,1},};
std::vector<Arc> arcs_37_2={{9,4},};
std::vector<Arc> arcs_37_3={{9,5},};
std::vector<Arc> arcs_37_4={{0,4},};
std::vector<Arc> arcs_37_5={{20,3},{0,5},};
std::vector<DFAState> states_37={arcs_37_0,arcs_37_1,arcs_37_2,arcs_37_3,arcs_37_4,arcs_37_5,};
DFA dfa_37={293,"expr_stmt",0,states_37,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<Arc> arcs_38_0={{93,1},};
std::vector<Arc> arcs_38_1={{0,1},};
std::vector<DFAState> states_38={arcs_38_0,arcs_38_1,};
DFA dfa_38={294,"pass_stmt",0,states_38,{64,"\000\000\000\000\000\000\000\000\000\000\000\040\000\000\000\000"}};

std::vector<Arc> arcs_39_0={{94,1},{95,2},{96,3},{97,4},};
std::vector<Arc> arcs_39_1={{0,1},};
std::vector<Arc> arcs_39_2={{0,2},};
std::vector<Arc> arcs_39_3={{0,3},};
std::vector<Arc> arcs_39_4={{0,4},};
std::vector<DFAState> states_39={arcs_39_0,arcs_39_1,arcs_39_2,arcs_39_3,arcs_39_4,};
DFA dfa_39={295,"flow_stmt",0,states_39,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\074\000\000\000"}};

std::vector<Arc> arcs_40_0={{98,1},};
std::vector<Arc> arcs_40_1={{0,1},};
std::vector<DFAState> states_40={arcs_40_0,arcs_40_1,};
DFA dfa_40={296,"break_stmt",0,states_40,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\004\000\000\000"}};

std::vector<Arc> arcs_41_0={{99,1},};
std::vector<Arc> arcs_41_1={{0,1},};
std::vector<DFAState> states_41={arcs_41_0,arcs_41_1,};
DFA dfa_41={297,"continue_stmt",0,states_41,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\010\000\000\000"}};

std::vector<Arc> arcs_42_0={{100,1},};
std::vector<Arc> arcs_42_1={{9,2},{0,1},};
std::vector<Arc> arcs_42_2={{0,2},};
std::vector<DFAState> states_42={arcs_42_0,arcs_42_1,arcs_42_2,};
DFA dfa_42={298,"return_stmt",0,states_42,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\020\000\000\000"}};

std::vector<Arc> arcs_43_0={{101,1},};
std::vector<Arc> arcs_43_1={{9,2},{0,1},};
std::vector<Arc> arcs_43_2={{0,2},};
std::vector<DFAState> states_43={arcs_43_0,arcs_43_1,arcs_43_2,};
DFA dfa_43={299,"yield_expr",0,states_43,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\040\000\000\000"}};

std::vector<Arc> arcs_44_0={{81,1},{103,2},};
std::vector<Arc> arcs_44_1={{0,1},};
std::vector<Arc> arcs_44_2={{0,2},};
std::vector<DFAState> states_44={arcs_44_0,arcs_44_1,arcs_44_2,};
DFA dfa_44={300,"comp_iter",0,states_44,{64,"\000\000\000\001\000\000\000\000\000\000\000\000\000\001\000\000"}};

std::vector<Arc> arcs_45_0={{104,1},};
std::vector<Arc> arcs_45_1={{82,2},};
std::vector<Arc> arcs_45_2={{105,3},};
std::vector<Arc> arcs_45_3={{23,4},};
std::vector<Arc> arcs_45_4={{102,5},{0,4},};
std::vector<Arc> arcs_45_5={{0,5},};
std::vector<DFAState> states_45={arcs_45_0,arcs_45_1,arcs_45_2,arcs_45_3,arcs_45_4,arcs_45_5,};
DFA dfa_45={301,"comp_for",0,states_45,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\000\001\000\000"}};

std::vector<Arc> arcs_46_0={{24,1},};
std::vector<Arc> arcs_46_1={{23,2},};
std::vector<Arc> arcs_46_2={{102,3},{0,2},};
std::vector<Arc> arcs_46_3={{0,3},};
std::vector<DFAState> states_46={arcs_46_0,arcs_46_1,arcs_46_2,arcs_46_3,};
DFA dfa_46={302,"comp_if",0,states_46,{64,"\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_47_0={{106,1},{107,2},{108,3},{109,4},{110,5},{111,6},{112,7},{113,8},{114,9},{115,10},{116,11},{117,12},};
std::vector<Arc> arcs_47_1={{0,1},};
std::vector<Arc> arcs_47_2={{0,2},};
std::vector<Arc> arcs_47_3={{0,3},};
std::vector<Arc> arcs_47_4={{0,4},};
std::vector<Arc> arcs_47_5={{0,5},};
std::vector<Arc> arcs_47_6={{0,6},};
std::vector<Arc> arcs_47_7={{0,7},};
std::vector<Arc> arcs_47_8={{0,8},};
std::vector<Arc> arcs_47_9={{0,9},};
std::vector<Arc> arcs_47_10={{0,10},};
std::vector<Arc> arcs_47_11={{0,11},};
std::vector<Arc> arcs_47_12={{0,12},};
std::vector<DFAState> states_47={arcs_47_0,arcs_47_1,arcs_47_2,arcs_47_3,arcs_47_4,arcs_47_5,arcs_47_6,arcs_47_7,arcs_47_8,arcs_47_9,arcs_47_10,arcs_47_11,arcs_47_12,};
DFA dfa_47={303,"augassign",0,states_47,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\000\374\077\000"}};

std::vector<Arc> arcs_48_0={{3,1},{2,2},};
std::vector<Arc> arcs_48_1={{0,1},};
std::vector<Arc> arcs_48_2={{118,3},};
std::vector<Arc> arcs_48_3={{6,4},};
std::vector<Arc> arcs_48_4={{6,4},{119,5},};
std::vector<Arc> arcs_48_5={{0,5},};
std::vector<DFAState> states_48={arcs_48_0,arcs_48_1,arcs_48_2,arcs_48_3,arcs_48_4,arcs_48_5,};
DFA dfa_48={304,"suite",0,states_48,{64,"\004\020\001\100\000\000\014\202\344\007\000\054\074\000\000\000"}};

std::vector<Arc> arcs_49_0={{120,1},{121,2},{122,3},{10,4},{123,5},};
std::vector<Arc> arcs_49_1={{0,1},};
std::vector<Arc> arcs_49_2={{0,2},};
std::vector<Arc> arcs_49_3={{0,3},};
std::vector<Arc> arcs_49_4={{0,4},};
std::vector<Arc> arcs_49_5={{0,5},};
std::vector<DFAState> states_49={arcs_49_0,arcs_49_1,arcs_49_2,arcs_49_3,arcs_49_4,arcs_49_5,};
DFA dfa_49={305,"compound_stmt",0,states_49,{64,"\000\010\000\001\000\000\000\000\000\000\000\000\000\001\000\140"}};

std::vector<Arc> arcs_50_0={{24,1},};
std::vector<Arc> arcs_50_1={{21,2},};
std::vector<Arc> arcs_50_2={{14,3},};
std::vector<Arc> arcs_50_3={{15,4},};
std::vector<Arc> arcs_50_4={{124,5},{25,6},{0,4},};
std::vector<Arc> arcs_50_5={{21,7},};
std::vector<Arc> arcs_50_6={{14,8},};
std::vector<Arc> arcs_50_7={{14,9},};
std::vector<Arc> arcs_50_8={{15,10},};
std::vector<Arc> arcs_50_9={{15,11},};
std::vector<Arc> arcs_50_10={{0,10},};
std::vector<Arc> arcs_50_11={{124,5},{25,6},{0,11},};
std::vector<DFAState> states_50={arcs_50_0,arcs_50_1,arcs_50_2,arcs_50_3,arcs_50_4,arcs_50_5,arcs_50_6,arcs_50_7,arcs_50_8,arcs_50_9,arcs_50_10,arcs_50_11,};
DFA dfa_50={306,"if_stmt",0,states_50,{64,"\000\000\000\001\000\000\000\000\000\000\000\000\000\000\000\000"}};

std::vector<Arc> arcs_51_0={{125,1},};
std::vector<Arc> arcs_51_1={{21,2},};
std::vector<Arc> arcs_51_2={{14,3},};
std::vector<Arc> arcs_51_3={{15,4},};
std::vector<Arc> arcs_51_4={{25,5},{0,4},};
std::vector<Arc> arcs_51_5={{14,6},};
std::vector<Arc> arcs_51_6={{15,7},};
std::vector<Arc> arcs_51_7={{0,7},};
std::vector<DFAState> states_51={arcs_51_0,arcs_51_1,arcs_51_2,arcs_51_3,arcs_51_4,arcs_51_5,arcs_51_6,arcs_51_7,};
DFA dfa_51={307,"while_stmt",0,states_51,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\040"}};

std::vector<Arc> arcs_52_0={{104,1},};
std::vector<Arc> arcs_52_1={{82,2},};
std::vector<Arc> arcs_52_2={{105,3},};
std::vector<Arc> arcs_52_3={{9,4},};
std::vector<Arc> arcs_52_4={{14,5},};
std::vector<Arc> arcs_52_5={{15,6},};
std::vector<Arc> arcs_52_6={{25,7},{0,6},};
std::vector<Arc> arcs_52_7={{14,8},};
std::vector<Arc> arcs_52_8={{15,9},};
std::vector<Arc> arcs_52_9={{0,9},};
std::vector<DFAState> states_52={arcs_52_0,arcs_52_1,arcs_52_2,arcs_52_3,arcs_52_4,arcs_52_5,arcs_52_6,arcs_52_7,arcs_52_8,arcs_52_9,};
DFA dfa_52={308,"for_stmt",0,states_52,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\000\001\000\000"}};

std::vector<Arc> arcs_53_0={{126,1},};
std::vector<Arc> arcs_53_1={{12,2},};
std::vector<Arc> arcs_53_2={{16,3},{14,4},};
std::vector<Arc> arcs_53_3={{75,5},{18,6},};
std::vector<Arc> arcs_53_4={{15,7},};
std::vector<Arc> arcs_53_5={{18,6},};
std::vector<Arc> arcs_53_6={{14,4},};
std::vector<Arc> arcs_53_7={{0,7},};
std::vector<DFAState> states_53={arcs_53_0,arcs_53_1,arcs_53_2,arcs_53_3,arcs_53_4,arcs_53_5,arcs_53_6,arcs_53_7,};
DFA dfa_53={309,"classdef",0,states_53,{64,"\000\000\000\000\000\000\000\000\000\000\000\000\000\000\000\100"}};

std::vector<Arc> arcs_54_0={{21,1},};
std::vector<Arc> arcs_54_1={{14,2},};
std::vector<Arc> arcs_54_2={{21,3},};
std::vector<Arc> arcs_54_3={{81,4},{22,5},{22,5},{0,3},};
std::vector<Arc> arcs_54_4={{0,4},};
std::vector<Arc> arcs_54_5={{21,6},{0,5},};
std::vector<Arc> arcs_54_6={{14,7},};
std::vector<Arc> arcs_54_7={{21,8},};
std::vector<Arc> arcs_54_8={{22,5},{22,5},{0,8},};
std::vector<DFAState> states_54={arcs_54_0,arcs_54_1,arcs_54_2,arcs_54_3,arcs_54_4,arcs_54_5,arcs_54_6,arcs_54_7,arcs_54_8,};
DFA dfa_54={310,"dictorsetmaker",0,states_54,{64,"\000\020\001\100\000\000\014\202\344\007\000\000\000\000\000\000"}};

std::vector<DFA> dfas={
    dfa_0,
    dfa_1,
    dfa_2,
    dfa_3,
    dfa_4,
    dfa_5,
    dfa_6,
    dfa_7,
    dfa_8,
    dfa_9,
    dfa_10,
    dfa_11,
    dfa_12,
    dfa_13,
    dfa_14,
    dfa_15,
    dfa_16,
    dfa_17,
    dfa_18,
    dfa_19,
    dfa_20,
    dfa_21,
    dfa_22,
    dfa_23,
    dfa_24,
    dfa_25,
    dfa_26,
    dfa_27,
    dfa_28,
    dfa_29,
    dfa_30,
    dfa_31,
    dfa_32,
    dfa_33,
    dfa_34,
    dfa_35,
    dfa_36,
    dfa_37,
    dfa_38,
    dfa_39,
    dfa_40,
    dfa_41,
    dfa_42,
    dfa_43,
    dfa_44,
    dfa_45,
    dfa_46,
    dfa_47,
    dfa_48,
    dfa_49,
    dfa_50,
    dfa_51,
    dfa_52,
    dfa_53,
    dfa_54,
};
Grammar grammar(labels,dfas);

Grammar *GetGrammar(){
    return &grammar;
}
std::string NonTerminalMap(int i){
    if (i==256) return "single_input";
    if (i==257) return "file_input";
    if (i==258) return "eval_input";
    if (i==259) return "funcdef";
    if (i==260) return "parameters";
    if (i==261) return "typedargslist";
    if (i==262) return "tfpdef";
    if (i==263) return "test";
    if (i==264) return "or_test";
    if (i==265) return "and_test";
    if (i==266) return "not_test";
    if (i==267) return "comparison";
    if (i==268) return "comp_op";
    if (i==269) return "expr";
    if (i==270) return "xor_expr";
    if (i==271) return "and_expr";
    if (i==272) return "shift_expr";
    if (i==273) return "arith_expr";
    if (i==274) return "term";
    if (i==275) return "factor";
    if (i==276) return "power";
    if (i==277) return "atom_expr";
    if (i==278) return "atom";
    if (i==279) return "trailer";
    if (i==280) return "subscriptlist";
    if (i==281) return "subscript";
    if (i==282) return "sliceop";
    if (i==283) return "argument";
    if (i==284) return "testlist_comp";
    if (i==285) return "arglist";
    if (i==286) return "testlist";
    if (i==287) return "exprlist";
    if (i==288) return "stmt";
    if (i==289) return "simple_stmt";
    if (i==290) return "small_stmt";
    if (i==291) return "nonlocal_stmt";
    if (i==292) return "global_stmt";
    if (i==293) return "expr_stmt";
    if (i==294) return "pass_stmt";
    if (i==295) return "flow_stmt";
    if (i==296) return "break_stmt";
    if (i==297) return "continue_stmt";
    if (i==298) return "return_stmt";
    if (i==299) return "yield_expr";
    if (i==300) return "comp_iter";
    if (i==301) return "comp_for";
    if (i==302) return "comp_if";
    if (i==303) return "augassign";
    if (i==304) return "suite";
    if (i==305) return "compound_stmt";
    if (i==306) return "if_stmt";
    if (i==307) return "while_stmt";
    if (i==308) return "for_stmt";
    if (i==309) return "classdef";
    if (i==310) return "dictorsetmaker";
    assert(false);
}
